coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.3%
    patch:
      default:
        target: 80%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "test-setup.ts"
  - "__tests__/**"
  - "scripts/**"
  - "drizzle/**"
  - "*.config.*"
